{
 "title": "Kubernetes / Storage",
 "tags": [
  "kubernetes",
  "prometheus",
  "storage",
  "performance",
  "disk"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (directory_size_bytes)\n    and\n    (predict_linear(directory_size_bytes[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (directory_size_bytes)\n    and\n    (predict_linear(directory_size_bytes[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (directory_size_bytes)\n    and\n    (predict_linear(directory_size_bytes[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n  (sum by (persistentvolume) (directory_size_bytes) / sum by (persistentvolume) (kube_persistentvolume_capacity_bytes)) > 0.8\n) or vector(0)\n"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Storage Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolume,storageclass) (kube_persistentvolume_info)"
    },
    {
     "expr": "sum by (persistentvolume) (kube_persistentvolume_capacity_bytes)"
    },
    {
     "expr": "sum by (persistentvolume) (directory_size_bytes)"
    },
    {
     "expr": "sum by (persistentvolume) (kube_persistentvolume_capacity_bytes) - sum by (persistentvolume) (directory_size_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=~\"(Pending|Lost)\"}) by (persistentvolume)\n"
    },
    {
     "expr": "sum by (persistentvolume) (directory_size_bytes) / sum by (persistentvolume) (kube_persistentvolume_capacity_bytes) * 100"
    },
    {
     "expr": "  sum by (persistentvolume, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\"))\n"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (\n  label_replace(\n    last_over_time(directory_size_bytes[1h]), \n    \"persistentvolumeclaim\", \"$1\", \n    \"persistentvolume\", \"(.*)\"\n  ) * on(persistentvolume) group_left(persistentvolumeclaim) (\n    label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n  )\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Storage Classes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  }
 ]
}